# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Ci/CD pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
        name: Get flutter version
      - run: flutter --version
        name: Get dependencies
      - run: flutter pub get
        name: Run unit test
      - run: flutter test
        name: publish artifact
      - run: flutter build aar
        name: Upload AAR to Jitpack
      - uses: actions/upload-artifact@v4  # Use Jitpack action
        with:
          name: my-artifact
          path: /home/runner/work/nice_flutter_module/nice_flutter_module/build/host/outputs/repo  
      - uses: shivlingvp/jitpack-action@v2  # Use Jitpack action
        # Alternatively, use Jitpack/jitpack-action@v1 (if v2 unavailable)
        with:
          username: oluwasegunilori  # Replace with your username
          token: ${{ secrets.TOKEN_NAME }}  # Access token with upload rights
          build_type: 'NATIVE'  # Specify build type as 'NATIVE' for Flutter modules    