# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Ci/CD pipeline
env: 
  MAVEN_REPO_USERNAME: ${{ secrets.MAVEN_REPO_USERNAME }}
  MAVEN_REPO_PASSWORD: ${{ secrets.MAVEN_REPO_PASSWORD }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
        name: Get flutter version
      - run: flutter --version
        name: Get dependencies
      - run: flutter pub get
        name: Run unit test
      - run: flutter test
        name: publish artifact
      - run: flutter build aar
        name: Publish to Maven
      - run: |
          cd .android
          ./gradlew publish
          