# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Ci/CD pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
        name: Get flutter version
      - run: flutter --version
        name: Get dependencies
      - run: flutter pub get
      - uses: "anything"
        name: Get access to artifactory
        with:
          access_token: ${{ secrets.LOC_ACCESS_TOKEN }}
        env:
          JF_URL: ${{ secrets.JF_URL }}
      - run: dart pub token add "$env:JF_URL"
        name: Run unit test
      - run: flutter test
        name: Build android artifacts
      - run: dart pub publis
